import * as AWS from "@aws-sdk/client-s3";

import { TextractClient } from "@aws-sdk/client-textract";

export const MAPS_API_KEY = "AIzaSyA_jzgsNBD9FklOoEVmmdAH9nufXVgqQIE";

export const countries = [
  { value: "Israel", phoneCode: "+972", code: "IL" },
  { value: "Afghanistan", phoneCode: "+93", code: "AF" },
  { value: "Albania", phoneCode: "+355", code: "AL" },
  { value: "Algeria", phoneCode: "+213", code: "DZ" },
  { value: "AmericanSamoa", phoneCode: "+1 684", code: "AS" },
  { value: "Andorra", phoneCode: "+376", code: "AD" },
  { value: "Angola", phoneCode: "+244", code: "AO" },
  { value: "Anguilla", phoneCode: "+1 264", code: "AI" },
  { value: "Antigua and Barbuda", phoneCode: "+1268", code: "AG" },
  { value: "Argentina", phoneCode: "+54", code: "AR" },
  { value: "Armenia", phoneCode: "+374", code: "AM" },
  { value: "Aruba", phoneCode: "+297", code: "AW" },
  { value: "Australia", phoneCode: "+61", code: "AU" },
  { value: "Austria", phoneCode: "+43", code: "AT" },
  { value: "Azerbaijan", phoneCode: "+994", code: "AZ" },
  { value: "Bahamas", phoneCode: "+1 242", code: "BS" },
  { value: "Bahrain", phoneCode: "+973", code: "BH" },
  { value: "Bangladesh", phoneCode: "+880", code: "BD" },
  { value: "Barbados", phoneCode: "+1 246", code: "BB" },
  { value: "Belarus", phoneCode: "+375", code: "BY" },
  { value: "Belgium", phoneCode: "+32", code: "BE" },
  { value: "Belize", phoneCode: "+501", code: "BZ" },
  { value: "Benin", phoneCode: "+229", code: "BJ" },
  { value: "Bermuda", phoneCode: "+1 441", code: "BM" },
  { value: "Bhutan", phoneCode: "+975", code: "BT" },
  { value: "Bosnia and Herzegovina", phoneCode: "+387", code: "BA" },
  { value: "Botswana", phoneCode: "+267", code: "BW" },
  { value: "Brazil", phoneCode: "+55", code: "BR" },
  { value: "British Indian Ocean Territory", phoneCode: "+246", code: "IO" },
  { value: "Bulgaria", phoneCode: "+359", code: "BG" },
  { value: "Burkina Faso", phoneCode: "+226", code: "BF" },
  { value: "Burundi", phoneCode: "+257", code: "BI" },
  { value: "Cambodia", phoneCode: "+855", code: "KH" },
  { value: "Cameroon", phoneCode: "+237", code: "CM" },
  { value: "Canada", phoneCode: "+1", code: "CA" },
  { value: "Cape Verde", phoneCode: "+238", code: "CV" },
  { value: "Cayman Islands", phoneCode: "+ 345", code: "KY" },
  { value: "Central African Republic", phoneCode: "+236", code: "CF" },
  { value: "Chad", phoneCode: "+235", code: "TD" },
  { value: "Chile", phoneCode: "+56", code: "CL" },
  { value: "China", phoneCode: "+86", code: "CN" },
  { value: "Christmas Island", phoneCode: "+61", code: "CX" },
  { value: "Colombia", phoneCode: "+57", code: "CO" },
  { value: "Comoros", phoneCode: "+269", code: "KM" },
  { value: "Congo", phoneCode: "+242", code: "CG" },
  { value: "Cook Islands", phoneCode: "+682", code: "CK" },
  { value: "Costa Rica", phoneCode: "+506", code: "CR" },
  { value: "Croatia", phoneCode: "+385", code: "HR" },
  { value: "Cuba", phoneCode: "+53", code: "CU" },
  { value: "Cyprus", phoneCode: "+537", code: "CY" },
  { value: "Czech Republic", phoneCode: "+420", code: "CZ" },
  { value: "Denmark", phoneCode: "+45", code: "DK" },
  { value: "Djibouti", phoneCode: "+253", code: "DJ" },
  { value: "Dominica", phoneCode: "+1 767", code: "DM" },
  { value: "Dominican Republic", phoneCode: "+1 849", code: "DO" },
  { value: "Ecuador", phoneCode: "+593", code: "EC" },
  { value: "Egypt", phoneCode: "+20", code: "EG" },
  { value: "El Salvador", phoneCode: "+503", code: "SV" },
  { value: "Equatorial Guinea", phoneCode: "+240", code: "GQ" },
  { value: "Eritrea", phoneCode: "+291", code: "ER" },
  { value: "Estonia", phoneCode: "+372", code: "EE" },
  { value: "Ethiopia", phoneCode: "+251", code: "ET" },
  { value: "Faroe Islands", phoneCode: "+298", code: "FO" },
  { value: "Fiji", phoneCode: "+679", code: "FJ" },
  { value: "Finland", phoneCode: "+358", code: "FI" },
  { value: "France", phoneCode: "+33", code: "FR" },
  { value: "French Guiana", phoneCode: "+594", code: "GF" },
  { value: "French Polynesia", phoneCode: "+689", code: "PF" },
  { value: "Gabon", phoneCode: "+241", code: "GA" },
  { value: "Gambia", phoneCode: "+220", code: "GM" },
  { value: "Georgia", phoneCode: "+995", code: "GE" },
  { value: "Germany", phoneCode: "+49", code: "DE" },
  { value: "Ghana", phoneCode: "+233", code: "GH" },
  { value: "Gibraltar", phoneCode: "+350", code: "GI" },
  { value: "Greece", phoneCode: "+30", code: "GR" },
  { value: "Greenland", phoneCode: "+299", code: "GL" },
  { value: "Grenada", phoneCode: "+1 473", code: "GD" },
  { value: "Guadeloupe", phoneCode: "+590", code: "GP" },
  { value: "Guam", phoneCode: "+1 671", code: "GU" },
  { value: "Guatemala", phoneCode: "+502", code: "GT" },
  { value: "Guinea", phoneCode: "+224", code: "GN" },
  { value: "Guinea-Bissau", phoneCode: "+245", code: "GW" },
  { value: "Guyana", phoneCode: "+595", code: "GY" },
  { value: "Haiti", phoneCode: "+509", code: "HT" },
  { value: "Honduras", phoneCode: "+504", code: "HN" },
  { value: "Hungary", phoneCode: "+36", code: "HU" },
  { value: "Iceland", phoneCode: "+354", code: "IS" },
  { value: "India", phoneCode: "+91", code: "IN" },
  { value: "Indonesia", phoneCode: "+62", code: "ID" },
  { value: "Iraq", phoneCode: "+964", code: "IQ" },
  { value: "Ireland", phoneCode: "+353", code: "IE" },
  { value: "Israel", phoneCode: "+972", code: "IL" },
  { value: "Italy", phoneCode: "+39", code: "IT" },
  { value: "Jamaica", phoneCode: "+1 876", code: "JM" },
  { value: "Japan", phoneCode: "+81", code: "JP" },
  { value: "Jordan", phoneCode: "+962", code: "JO" },
  { value: "Kazakhstan", phoneCode: "+7 7", code: "KZ" },
  { value: "Kenya", phoneCode: "+254", code: "KE" },
  { value: "Kiribati", phoneCode: "+686", code: "KI" },
  { value: "Kuwait", phoneCode: "+965", code: "KW" },
  { value: "Kyrgyzstan", phoneCode: "+996", code: "KG" },
  { value: "Latvia", phoneCode: "+371", code: "LV" },
  { value: "Lebanon", phoneCode: "+961", code: "LB" },
  { value: "Lesotho", phoneCode: "+266", code: "LS" },
  { value: "Liberia", phoneCode: "+231", code: "LR" },
  { value: "Liechtenstein", phoneCode: "+423", code: "LI" },
  { value: "Lithuania", phoneCode: "+370", code: "LT" },
  { value: "Luxembourg", phoneCode: "+352", code: "LU" },
  { value: "Madagascar", phoneCode: "+261", code: "MG" },
  { value: "Malawi", phoneCode: "+265", code: "MW" },
  { value: "Malaysia", phoneCode: "+60", code: "MY" },
  { value: "Maldives", phoneCode: "+960", code: "MV" },
  { value: "Mali", phoneCode: "+223", code: "ML" },
  { value: "Malta", phoneCode: "+356", code: "MT" },
  { value: "Marshall Islands", phoneCode: "+692", code: "MH" },
  { value: "Martinique", phoneCode: "+596", code: "MQ" },
  { value: "Mauritania", phoneCode: "+222", code: "MR" },
  { value: "Mauritius", phoneCode: "+230", code: "MU" },
  { value: "Mayotte", phoneCode: "+262", code: "YT" },
  { value: "Mexico", phoneCode: "+52", code: "MX" },
  { value: "Monaco", phoneCode: "+377", code: "MC" },
  { value: "Mongolia", phoneCode: "+976", code: "MN" },
  { value: "Montenegro", phoneCode: "+382", code: "ME" },
  { value: "Montserrat", phoneCode: "+1664", code: "MS" },
  { value: "Morocco", phoneCode: "+212", code: "MA" },
  { value: "Myanmar", phoneCode: "+95", code: "MM" },
  { value: "Namibia", phoneCode: "+264", code: "NA" },
  { value: "Nauru", phoneCode: "+674", code: "NR" },
  { value: "Nepal", phoneCode: "+977", code: "NP" },
  { value: "Netherlands", phoneCode: "+31", code: "NL" },
  { value: "Netherlands Antilles", phoneCode: "+599", code: "AN" },
  { value: "New Caledonia", phoneCode: "+687", code: "NC" },
  { value: "New Zealand", phoneCode: "+64", code: "NZ" },
  { value: "Nicaragua", phoneCode: "+505", code: "NI" },
  { value: "Niger", phoneCode: "+227", code: "NE" },
  { value: "Nigeria", phoneCode: "+234", code: "NG" },
  { value: "Niue", phoneCode: "+683", code: "NU" },
  { value: "Norfolk Island", phoneCode: "+672", code: "NF" },
  { value: "Northern Mariana Islands", phoneCode: "+1 670", code: "MP" },
  { value: "Norway", phoneCode: "+47", code: "NO" },
  { value: "Oman", phoneCode: "+968", code: "OM" },
  { value: "Pakistan", phoneCode: "+92", code: "PK" },
  { value: "Palau", phoneCode: "+680", code: "PW" },
  { value: "Panama", phoneCode: "+507", code: "PA" },
  { value: "Papua New Guinea", phoneCode: "+675", code: "PG" },
  { value: "Paraguay", phoneCode: "+595", code: "PY" },
  { value: "Peru", phoneCode: "+51", code: "PE" },
  { value: "Philippines", phoneCode: "+63", code: "PH" },
  { value: "Poland", phoneCode: "+48", code: "PL" },
  { value: "Portugal", phoneCode: "+351", code: "PT" },
  { value: "Puerto Rico", phoneCode: "+1 939", code: "PR" },
  { value: "Qatar", phoneCode: "+974", code: "QA" },
  { value: "Romania", phoneCode: "+40", code: "RO" },
  { value: "Rwanda", phoneCode: "+250", code: "RW" },
  { value: "Samoa", phoneCode: "+685", code: "WS" },
  { value: "San Marino", phoneCode: "+378", code: "SM" },
  { value: "Saudi Arabia", phoneCode: "+966", code: "SA" },
  { value: "Senegal", phoneCode: "+221", code: "SN" },
  { value: "Serbia", phoneCode: "+381", code: "RS" },
  { value: "Seychelles", phoneCode: "+248", code: "SC" },
  { value: "Sierra Leone", phoneCode: "+232", code: "SL" },
  { value: "Singapore", phoneCode: "+65", code: "SG" },
  { value: "Slovakia", phoneCode: "+421", code: "SK" },
  { value: "Slovenia", phoneCode: "+386", code: "SI" },
  { value: "Solomon Islands", phoneCode: "+677", code: "SB" },
  { value: "South Africa", phoneCode: "+27", code: "ZA" },
  {
    value: "South Georgia and the South Sandwich Islands",
    phoneCode: "+500",
    code: "GS",
  },
  { value: "Spain", phoneCode: "+34", code: "ES" },
  { value: "Sri Lanka", phoneCode: "+94", code: "LK" },
  { value: "Sudan", phoneCode: "+249", code: "SD" },
  { value: "Suriname", phoneCode: "+597", code: "SR" },
  { value: "Swaziland", phoneCode: "+268", code: "SZ" },
  { value: "Sweden", phoneCode: "+46", code: "SE" },
  { value: "Switzerland", phoneCode: "+41", code: "CH" },
  { value: "Tajikistan", phoneCode: "+992", code: "TJ" },
  { value: "Thailand", phoneCode: "+66", code: "TH" },
  { value: "Togo", phoneCode: "+228", code: "TG" },
  { value: "Tokelau", phoneCode: "+690", code: "TK" },
  { value: "Tonga", phoneCode: "+676", code: "TO" },
  { value: "Trinidad and Tobago", phoneCode: "+1 868", code: "TT" },
  { value: "Tunisia", phoneCode: "+216", code: "TN" },
  { value: "Turkey", phoneCode: "+90", code: "TR" },
  { value: "Turkmenistan", phoneCode: "+993", code: "TM" },
  { value: "Turks and Caicos Islands", phoneCode: "+1 649", code: "TC" },
  { value: "Tuvalu", phoneCode: "+688", code: "TV" },
  { value: "Uganda", phoneCode: "+256", code: "UG" },
  { value: "Ukraine", phoneCode: "+380", code: "UA" },
  { value: "United Arab Emirates", phoneCode: "+971", code: "AE" },
  { value: "United Kingdom", phoneCode: "+44", code: "GB" },
  { value: "United States", phoneCode: "+1", code: "US" },
  { value: "Uruguay", phoneCode: "+598", code: "UY" },
  { value: "Uzbekistan", phoneCode: "+998", code: "UZ" },
  { value: "Vanuatu", phoneCode: "+678", code: "VU" },
  { value: "Wallis and Futuna", phoneCode: "+681", code: "WF" },
  { value: "Yemen", phoneCode: "+967", code: "YE" },
  { value: "Zambia", phoneCode: "+260", code: "ZM" },
  { value: "Zimbabwe", phoneCode: "+263", code: "ZW" },
  { value: "land Islands", phoneCode: "", code: "AX" },
  { value: "Antarctica", phoneCode: null, code: "AQ" },
  { value: "Bolivia, Plurinational State of", phoneCode: "+591", code: "BO" },
  { value: "Brunei Darussalam", phoneCode: "+673", code: "BN" },
  { value: "Cocos (Keeling) Islands", phoneCode: "+61", code: "CC" },
  {
    value: "Congo, The Democratic Republic of the",
    phoneCode: "+243",
    code: "CD",
  },
  { value: "Cote d'Ivoire", phoneCode: "+225", code: "CI" },
  { value: "Falkland Islands (Malvinas)", phoneCode: "+500", code: "FK" },
  { value: "Guernsey", phoneCode: "+44", code: "GG" },
  { value: "Holy See (Vatican City State)", phoneCode: "+379", code: "VA" },
  { value: "Hong Kong", phoneCode: "+852", code: "HK" },
  { value: "Iran, Islamic Republic of", phoneCode: "+98", code: "IR" },
  { value: "Isle of Man", phoneCode: "+44", code: "IM" },
  { value: "Jersey", phoneCode: "+44", code: "JE" },
  {
    value: "Korea, Democratic People's Republic of",
    phoneCode: "+850",
    code: "KP",
  },
  { value: "Korea, Republic of", phoneCode: "+82", code: "KR" },
  { value: "Lao People's Democratic Republic", phoneCode: "+856", code: "LA" },
  { value: "Libyan Arab Jamahiriya", phoneCode: "+218", code: "LY" },
  { value: "Macao", phoneCode: "+853", code: "MO" },
  {
    value: "Macedonia, The Former Yugoslav Republic of",
    phoneCode: "+389",
    code: "MK",
  },
  { value: "Micronesia, Federated States of", phoneCode: "+691", code: "FM" },
  { value: "Moldova, Republic of", phoneCode: "+373", code: "MD" },
  { value: "Mozambique", phoneCode: "+258", code: "MZ" },
  { value: "Palestinian Territory, Occupied", phoneCode: "+970", code: "PS" },
  { value: "Pitcairn", phoneCode: "+872", code: "PN" },
  { value: "Réunion", phoneCode: "+262", code: "RE" },
  { value: "Russia", phoneCode: "+7", code: "RU" },
  { value: "Saint Barthélemy", phoneCode: "+590", code: "BL" },
  {
    value: "Saint Helena, Ascension and Tristan Da Cunha",
    phoneCode: "+290",
    code: "SH",
  },
  { value: "Saint Kitts and Nevis", phoneCode: "+1 869", code: "KN" },
  { value: "Saint Lucia", phoneCode: "+1 758", code: "LC" },
  { value: "Saint Martin", phoneCode: "+590", code: "MF" },
  { value: "Saint Pierre and Miquelon", phoneCode: "+508", code: "PM" },
  {
    value: "Saint Vincent and the Grenadines",
    phoneCode: "+1 784",
    code: "VC",
  },
  { value: "Sao Tome and Principe", phoneCode: "+239", code: "ST" },
  { value: "Somalia", phoneCode: "+252", code: "SO" },
  { value: "Svalbard and Jan Mayen", phoneCode: "+47", code: "SJ" },
  { value: "Syrian Arab Republic", phoneCode: "+963", code: "SY" },
  { value: "Taiwan, Province of China", phoneCode: "+886", code: "TW" },
  { value: "Tanzania, United Republic of", phoneCode: "+255", code: "TZ" },
  { value: "Timor-Leste", phoneCode: "+670", code: "TL" },
  { value: "Venezuela, Bolivarian Republic of", phoneCode: "+58", code: "VE" },
  { value: "Viet Nam", phoneCode: "+84", code: "VN" },
  { value: "Virgin Islands, British", phoneCode: "+1 284", code: "VG" },
  { value: "Virgin Islands, U.S.", phoneCode: "+1 340", code: "VI" },
];

export const REGION = "us-east-1";
export const AWS_ACCESS_KEY = "AKIAQFE66PH75BJ2TT7M";
export const AWS_SECRET_KEY = "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";
export const S3_BUCKET = "cdn.carbucks.com";

// export const REGION = "us-east-1";
// export const AWS_ACCESS_KEY = "AKIAQFE66PH7TC3R5QGO";
// export const AWS_SECRET_KEY = "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";
// export const S3_BUCKET = "cdn.carbucks.com";

export const STRIPE_KEY =
  "pk_test_51JqL6zCS8Gvq8h8zsJq0J31IgeIsVl3daaElhHfYuKtKH6Mqfoyg6GrAWVW2E58R4izAYRl7VuE04HUMZp2bAH";

export const client = new TextractClient({
  region: REGION,
  credentials: {
    accessKeyId: AWS_ACCESS_KEY,
    secretAccessKey: AWS_SECRET_KEY,
  },
});

export const s3Client = new AWS.S3({
  region: REGION,
  credentials: {
    accessKeyId: AWS_ACCESS_KEY,
    secretAccessKey: AWS_SECRET_KEY,
  },
});
